### PR TITLE
Transpile

### LINKED ISSUE #3: Incompatible with Safari
Log:

```
$ npm run build

> notebook-preview-demo@0.0.0 build /Users/rgbkrk/code/src/github.com/nteract/nbp-trial
> npm run clean && npm run build:webpack


> notebook-preview-demo@0.0.0 clean /Users/rgbkrk/code/src/github.com/nteract/nbp-trial
> rimraf dist


> notebook-preview-demo@0.0.0 build:webpack /Users/rgbkrk/code/src/github.com/nteract/nbp-trial
> cross-env NODE_ENV=production webpack --config webpack.config.prod.js

Hash: 7c58c29adad66177efb8
Version: webpack 1.13.0
Time: 5435ms
        Asset     Size  Chunks             Chunk Names
    bundle.js  2.39 MB       0  [emitted]  main
bundle.js.map  2.88 MB       0  [emitted]  main
   [0] multi main 28 bytes {0} [built]
    + 310 hidden modules

ERROR in bundle.js from UglifyJs
Unexpected token: name (Anser) [./~/anser/lib/index.js:28,0]
```

Related repo: https://github.com/rgbkrk/notebook-preview-demo

### PR DESCRIPTION
**Pull request by rgbkrk**
Closes #3

### CODE REVIEW

**Comment by rgbkrk** [comment]
This ensures code is ES5 all the way through. The alternate way of doing this is to rewrite the package in vanilla ES5. I kept the path to the package the same so it doesn't affect the API. Tests all pass too (locally, since Travis is not set up here).

**Comment by rgbkrk** [comment]
/cc @IonicaBizau 

I'm going to go ahead and fork for a bit since this is holding up a user from deploying with one of our open source components. Let me know when you have a chance to check this out.

**Comment by IonicaBizau** [comment]
Hmm, thanks. I need to know a little bit of context: would it not be better to bundle and babelify the things in your app? I use [`dist-it`](https://github.com/IonicaBizau/dist-it) to bundle and babelify the things.

**Comment by rgbkrk** [comment]
This and `ansi-to-json` are the _only_ dependencies that need to be babelified, across many other dependencies. Creating a build step to handle this one path deep down inside is a really awkward flow.

**Comment by IonicaBizau** [comment]
OK, will take care of this, hopefully this evening. 😁

**Comment by IonicaBizau** [comment]
:ship: **`1.0.2`** Probably bundling `ansi-to-json` is enough, but I bundled this one too.

**Pull request merged**
